[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
keystore = "4DS5K64SuWK6PmN1puZVtPouLWCqQDA3aE58MPPuDXu2"

[programs.localnet]
keystore = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/*"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = '.anchor\test-ledger'
rpc_port = 8899

[[test.validator.clone]]
address = "Sysvar1nstructions1111111111111111111111111"

[[test.validator.clone]]
address = "Secp256r1SigVerify1111111111111111111111111"
